// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_test_basarim_10_adet_guvenlikci_alin = "CgkIzoLC7dsGEAIQBg"; // <GPGSID>
        public const string achievement_grand_opening = "CgkIzoLC7dsGEAIQFA"; // <GPGSID>
        public const string achievement_museum_boss = "CgkIzoLC7dsGEAIQCQ"; // <GPGSID>
        public const string achievement_first_entry = "CgkIzoLC7dsGEAIQBQ"; // <GPGSID>
        public const string achievement_art_lover = "CgkIzoLC7dsGEAIQCA"; // <GPGSID>
        public const string achievement_start_mission = "CgkIzoLC7dsGEAIQEQ"; // <GPGSID>
        public const string achievement_first_visitor = "CgkIzoLC7dsGEAIQBw"; // <GPGSID>
        public const string achievement_art_collector = "CgkIzoLC7dsGEAIQDg"; // <GPGSID>
        public const string achievement_the_first_step_the_birth_of_art = "CgkIzoLC7dsGEAIQAw"; // <GPGSID>
        public const string achievement_crowd_management = "CgkIzoLC7dsGEAIQEA"; // <GPGSID>
        public const string achievement_statue_lover = "CgkIzoLC7dsGEAIQDw"; // <GPGSID>
        public const string achievement_buy_your_first_worker = "CgkIzoLC7dsGEAIQBA"; // <GPGSID>
        public const string achievement_let_workers_work = "CgkIzoLC7dsGEAIQEg"; // <GPGSID>
        public const string achievement_worker_boss = "CgkIzoLC7dsGEAIQDQ"; // <GPGSID>
        public const string achievement_guitar_strum = "CgkIzoLC7dsGEAIQFQ"; // <GPGSID>
        public const string achievement_security_manager = "CgkIzoLC7dsGEAIQCw"; // <GPGSID>
        public const string achievement_cleaning_chief = "CgkIzoLC7dsGEAIQCg"; // <GPGSID>
        public const string achievement_introducing_art = "CgkIzoLC7dsGEAIQAg"; // <GPGSID>
        public const string achievement_housekeepers_active = "CgkIzoLC7dsGEAIQEw"; // <GPGSID>
        public const string achievement_the_power_of_music = "CgkIzoLC7dsGEAIQDA"; // <GPGSID>

}

